import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/app/providers";

// 引入Markdown样式
import "github-markdown-css/github-markdown.css";
// 引入代码高亮样式
import "highlight.js/styles/github.css";
//归一化样式
import "normalize.css";

import "./globals.css";

import TipsMessageContainer from "@/components/ui/TipsMessages";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TipsMessageContainer />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
